<?php

return [
    'user'              => 'user',
    'email'             => 'envelope',
    'post'              => 'book',
    'image'             => 'camera',
    'link'              => 'external-link',
    'comment'           => 'comment-o',
    'reply'             => 'comments-o',
    'rating'            => 'thumbs-o-up',
    'subscriber'        => 'rss',
    'time'              => 'clock-o',
    'edit'              => 'pencil-square-o',
    'delete'            => 'trash-o',
    'embed'             => 'file-code-o',
    'notification'      => 'bell-o',
    'placement'         => 'trophy',
    'reputation'        => 'star',
    'success'           => 'check',
    'warning'           => 'exclamation-triangle',
    'error'             => 'exclamation-triangle',
    'status'            => 'info-circle',
    'public'            => 'globe',
    'private'           => 'lock',
    'report'            => 'flag',
    'administration'    => 'pencil-square-o',
    'accept'            => 'check',
    'decline'           => 'times',
    'formatting'        => 'font',
];
